### ISSUE TITLE
Kicad6 plugin/footprint generator ?

### ISSUE THREAD

**Issue by wowtah** [TousstNicolas/JLC2KiCad_lib#13]
First of all, awesome script. Just what I needed :)

My request is to make this into a Kicad6 plugin, so that it can be used from the UI. 

Kicad has 'footprint generators', maybe it could become one of these:
![Kicad6_footprint](https://user-images.githubusercontent.com/30867746/170486806-24aec924-f62b-447b-8349-ea2f1877d83f.JPG)

Thanks for the great work!

**Comment by TousstNicolas** [comment]
Hi, thank you for opening this feature request. Unfortunately, I do not have time for now to develop any new features. 
I will close this issue for now, I might reopen it in the feature if I want to implement it.
