### ISSUE TITLE
-logging_level not working as expected

### ISSUE THREAD

**Issue by Bouni** [TousstNicolas/JLC2KiCad_lib#3]
I'm not sure if I got this right but passing `-logging_level DEBUG` didn't give me debug output on the console.

I changed [this line](https://github.com/TousstNicolas/JLC2KiCad_lib/blob/master/helper.py#L14) from `handler.setLevel(logging.INFO)` to `handler.setLevel(logging_level)` and then it worked as expected.

**Comment by TousstNicolas** [comment]
Yes, the debug messages are only written in the debug file if the --log_file option is set.
I print very large text in the Debug message (the response from the 3D model request for example, which can be 200k lines long for large components) which would flood the console and make it useless.

This is intended, but may be confusing so I will add this in the help message and in the readme.
