### ISSUE TITLE
Write parts to a single library, not one part per library

### ISSUE THREAD

**Issue by indrora** [TousstNicolas/JLC2KiCad_lib#36]
It would be really nice if the part was added onto an existing part library, rather than added to a directory of part libraries.

the Kicad library format for kicad6 is the same sexpr format that the footprints use.

**Comment by TousstNicolas** [comment]
Are you talking about the symbol libraries ? If yes, you can already do that by specifying he -schematic_lib option with the -dir option  to point to the library you want to append the symbol.
