### ISSUE TITLE
footprint problems

### ISSUE THREAD

**Issue by immortal-sniper1** [TousstNicolas/JLC2KiCad_lib#37]
**Describe the bug**
there is no courtyard for any footprint 
Also all footprints are labeled as THT (not a real problem but i noticed it when i was in 3D view )

**To Reproduce**
1. LCSC part # that caused the issue
2. Arguments used for the execution    vanilla arguments for both and C98732

**Expected behavior**
A clear and concise description of what you expected to happen.  some courtyard on that layer 

**Screenshots**

**Additional context**

**Comment by TousstNicolas** [comment]
Thank you for reporting this issue. 

Unfortunately, unless I missed it, there is no courtyard in the footprint are are not in present the easyeda editor, therefore, they won't be present in the kicad schematic. 

As for the THT components, I will check what is happening.
