### ISSUE TITLE
missing numpy dependency

### ISSUE THREAD

**Issue by vvuk** [TousstNicolas/JLC2KiCad_lib#39]
It looks like there's a missing dependency on numpy -- installing on a fairly clean/empty python setup, the main script complains about not being able to import numpy.  Manually installing it fixes the issue.

**Comment by TousstNicolas** [comment]
It was added in a PR and a did not saw it. It should never have been there. 

I removed it and you should now be able to install from pip without the numpy dependecy. 

Thanks for reporting the issue.
