### ISSUE TITLE
Footprint import bug

### ISSUE THREAD

**Issue by immortal-sniper1** [TousstNicolas/JLC2KiCad_lib#42]
**Describe the bug**
for some ICs the footprint is not imported properly 

**To Reproduce**
1. LCSC part # that caused the issue
2. Arguments used for the execution

es8388  is the one from who i noticed , the corner pads turned out round for some reason

**Expected behavior**

NORMAL QFP footprint 

**Screenshots**

**Additional context**

**Comment by TousstNicolas** [comment]
Fixed in 27a2f44dddb94c3d6c8b9b05d6765cdd458f37e5
