### ISSUE TITLE
incorrect filepath generated in the footprint file pointing to the 3d model

### ISSUE THREAD

**Issue by netweaver1970** [TousstNicolas/JLC2KiCad_lib#43]
**Describe the bug**
extra drive prefix was added to the filepath of the 3d model in the footprint file. It looks that the current path is used as a prefix instead of the absolute path as specified on the command line. Maybe check if it's an absolute path or relative path and act accordingly when composing the path to be entered in the footprint file pointing to the wrl file.

![image](https://user-images.githubusercontent.com/18028618/233428659-f98bce13-6af3-4b23-b1a2-4eabd32bd88d.png)

**Comment by TousstNicolas** [comment]
Thank you for reporting the issue.
Unfortunately, I do not have time to fix this issue for now. 

You should be able to implement this without difficulties and submit a PR afterwards.

Thanks for your understanding.
