### ISSUE TITLE
Multiple runs, adding new components, creates a broken Schematics file.

### ISSUE THREAD

**Issue by mikaelj** [TousstNicolas/JLC2KiCad_lib#45]
1.0.16

**How / what**
The merge doesn't work correctly when first running JLC2KiCadLib with a set of components, then adding components anywhere in in the list of parameters. 

**Result**
At the end of the file, there's a end-paren ), but instead of removing it, then adding the new symbol, you get lines looking like this:

    ) (symbol ...

instead of

    (symbol ...
    )

As a result, KiCad doesn't pick up the added symbols, since they're outside of the `(kicad_symbol_lib ...)` s-exp.

Removing the ) and placing it at the end makes the lib work, w/ KiCad finding the newly added symbol.

**Comment by TousstNicolas** [comment]
Hi, I could not reproduce the issue. 
Can you  please give me the arguments you used ?
