### ISSUE TITLE
canonical ".pretty" directory suffix is present when referencing footprints

### ISSUE THREAD

**Issue by vvuk** [TousstNicolas/JLC2KiCad_lib#47]
The issue description is a little confusing.  What's happening is:

- kicad canonically uses directories ending in `.pretty` to contain a bunch of `.kicad_mod` files for footprints
- when that footprint library is added, its name usually is not specified as `xxx.pretty`, but instead as `xxx`
- JLC2KiCad_Lib currently using the full name (or rather, the exact name specified) in the footprint designator in the symbol file.

So -- I typically use `JLC2KiCadLib -symbol_lib lcsc -footprint_lib lcsc.pretty --skip_existing ....` which puts things in a `lcsc.pretty` directory (good), I set up the footprint library with name `lcsc`.. but the symbol footprint reference looks like `lcsc.pretty:foo` when it should be `lcsc:foo`.

This is all just terrible convention, and can be fixed by just naming the symbol library "lcsc.pretty" (I think?) but I just hacked this locally to strip `.pretty` if it's present on the footprint library name in the symbol library.

**Comment by TousstNicolas** [comment]
Thanks for  reporting this issue. 
Fixed with 61d2852
