### ISSUE TITLE
After editing symbols library, parts can't be added.

### ISSUE THREAD

**Issue by jonsag** [TousstNicolas/JLC2KiCad_lib#48]
**Describe the bug**
After importing one or more parts and editing or removing parts, new parts added doesn't show.

This is probably the same issue as [#45](https://github.com/TousstNicolas/JLC2KiCad_lib/issues/45)

**To Reproduce**
1. LCSC part # that caused the issue
Any part#

2. Arguments used for the execution
>$ JLC2KiCadLib C599645 -dir ~/Documents/CodeWorkspace/myCAD/KiCadLibraries/JLC2KiCad -symbol_lib JLC2KiCad-symbol -footprint_lib JLC2KiCad-footprint

Then after deleting or editing a part using the Symbol Editor new parts added isn't shown either in the Symbol Editor or is selectable in 'Add a symbol'.

**Expected behavior**
Parts can be added, edited or deleted as usual.

**Screenshots**

**Additional context**
After adding a part kicad_sym has an erroneous ')' as shown.
New part in shown case is "C0603C104J3RAC7867_0_1" and is the last part in the file.

```
...
    )
    (property "LCSC" "C599645" (id 5) (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )

)    (symbol "C0603C104J3RAC7867_0_1"
      (polyline
        (pts
          (xy -0.5080010160020321 -2.0320040640081283)
          (xy -0.5080010160020321 2.0320040640081283)
...
```
After removing the parentheses it works as intended. ie

```
...
    )
    (property "LCSC" "C599645" (id 5) (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )

   (symbol "C0603C104J3RAC7867_0_1"
      (polyline
        (pts
          (xy -0.5080010160020321 -2.0320040640081283)
          (xy -0.5080010160020321 2.0320040640081283)
...
```

KiCad info:

```
KiCad x86_64 on x86_64

Version: 7.0.6-7.0.6~ubuntu22.04.1, release build

Libraries:
	wxWidgets 3.2.1
	FreeType 2.11.1
	HarfBuzz 6.0.0
	FontConfig 2.13.1
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.15

Platform: Linux Mint 21.2, 64 bit, Little endian, wxGTK, cinnamon, x11

Build Info:
	Date: Jul  7 2023 02:32:39
	wxWidgets: 3.2.1 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.74.0
	OCC: 7.5.2
	Curl: 7.88.1
	ngspice: 38
	Compiler: GCC 11.3.0 with C++ ABI 1016

Build settings:
	KICAD_SPICE=ON
```

Thanks
/jon

**Comment by TousstNicolas** [comment]
Hi, 
Thank you  for reporting this issue. 
It should be fixed with the latest commit. 
I will let you close the issue if you can confirm this is working as expected on your side.

**Comment by jonsag** [comment]
Great.
Haven't got the possibility to test at the moment, but as soon as
everything is OK, I will close it.

Thanks!
/jon
------------------------------------------------------------------------------
Jon Sagebrand

Jonix
Blacksta 6
611 95 Nyköping

***@***.***

070-694 67 34
------------------------------------------------------------------------------


Den sön 20 aug. 2023 kl 18:40 skrev Nicolas Toussaint <
***@***.***>:

**Comment by jonsag** [comment]
Seems to be working as it should now.
Good work!
Thanks

**Comment by jonsag** [comment]
Closing
