### ISSUE TITLE
Component OBJ/STEP file

### ISSUE THREAD

**Issue by ReinBentdal** [TousstNicolas/JLC2KiCad_lib#51]
Hi,
I would first of all thank you allot for making this library. It has truly been a game changer when working with JLCPCB!

**Is your feature request related to a problem? Please describe.**
Currently downloading wrl files from easyeda for the 3d models. However these does not export easily to CAD software like Fusion 360. 

**Describe the solution you'd like**
I know EasyEDA Pro has a feature to export as STEP or OBJ. Thus I would assume EasyEDA also stores their components in this format as well. Have you considered to implement something like this before?

**Comment by TousstNicolas** [comment]
Thanks to WesleyE for his PR.
