### ISSUE TITLE
Cannot connect symbol pins

### ISSUE THREAD

**Issue by dzid26** [TousstNicolas/JLC2KiCad_lib#57]
**Describe the bug**
Wire doesn't connect to symbol pins

**To Reproduce**
1. LCSC part # that caused the issue C2919500 
 

**Screenshots**
<img width="917" alt="image" src="https://github.com/TousstNicolas/JLC2KiCad_lib/assets/841061/3b4ecb58-4866-4e4e-a26f-edc0e8219a66">
<img width="870" alt="image" src="https://github.com/TousstNicolas/JLC2KiCad_lib/assets/841061/1fed4936-811f-4585-8a86-11cf98bf235c">

**Additional context**
I tried "aligning the schematic and also the symbol drawing in the editor. Didn't help.  
<img width="222" alt="image" src="https://github.com/TousstNicolas/JLC2KiCad_lib/assets/841061/7ff2354d-61ff-4291-b90e-53a41a5849bf">

**Comment by dzid26** [comment]
Oh, after moving the pin a bit 
![image](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/841061/65c6fcb7-9863-4b4b-99ea-9eec0228d56e)
and then back "where it was", the problem was fixed. 

I have a hunch that some iterative error accumulation is happening when pins are populated and only far top and far bottom pins are affected.

**Comment by TousstNicolas** [comment]
I rounded the position and length of the pins to the third digit, it should solve those imprecision errors.  

It works on C2919500.

I updated the Pip package, you  can test the update with `pip3 install JLC2KiCadLib==1.0.28`

I will let you close the issue if it works on your side.
