### ISSUE TITLE
Micro-USB Footprint: THT elements are missing in the footprint

### ISSUE THREAD

**Issue by besi** [TousstNicolas/JLC2KiCad_lib#62]
**Describe the bug**
I'm using a Micro USB Plug `JLC#C505111`. I do have a working footprint from the Kicad Standard Library for comparison. 
The Kicad Footprint is `Connector_USB:USB_Micro-B_Molex-105017-0001`

Now the EasyEDA-Converted footprint is missing a slot which goes through the PCB.
EasyEDA Preview shows the correct footprint:
https://jlcpcb.com/partdetail/Molex-1050171001/C505111

<img width="799" alt="Screenshot 2024-02-10 at 12 24 35" src="https://github.com/TousstNicolas/JLC2KiCad_lib/assets/160412/4ddd349f-810d-4478-8640-010d91d441c1">

However the downloaded footprint is missing the mentioned slot (Pad 8 on the EasyEDA preview):
<img width="545" alt="Screenshot 2024-02-10 at 12 21 09" src="https://github.com/TousstNicolas/JLC2KiCad_lib/assets/160412/8463abcb-b8a4-4f46-8164-cc2bfaf94d7c">
<img width="911" alt="Screenshot 2024-02-10 at 12 30 25" src="https://github.com/TousstNicolas/JLC2KiCad_lib/assets/160412/d33ec5f4-adbe-4f36-bde4-56f8bb8f6a29">

Another issue is that the round holes in the back (Pin6 and Pin7) also do not show up on the 3d Viewer so it's uncertain if those will get manufactured too.

I just started using this tool and I am very pleased you made the effort to create such a useful program. 
So thanks very much and thanks for looking into this issue ;-)

**Comment by TousstNicolas** [comment]
Hi, thanks for reporting this issue.

From the logs I see a beautiful `WARNING - footprint handler, pad : unknown assembly_process skiping pad n° : 8`. (with a little typo in it :open_mouth:  ) 

I will start looking into it.

**Comment by TousstNicolas** [comment]
The fix is available with version 1.0.30.
You should be able to update to this version.

I will let you close this issue if it works on your side.

![image](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/68825213/ae08739f-71c3-4fb7-9679-a9dee7a27dfb)
