### ISSUE TITLE
Windows 10, KiCad 7, Cannot Follow Instructions To Plugin Success ,  KicadModTree Not Sure.

### ISSUE THREAD

**Issue by ForrestErickson** [TousstNicolas/JLC2KiCad_lib#66]
**Describe the bug**
I have tried to follow the instructions to install on my Windows 10 system and KiCad 7.

I have the folder "JLC2KiCad_lib" in my plugin library
![image](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/5836181/460dd709-0276-4cba-bb01-681e4b3adffa)

When in a command windows, I ran the instructions for installing the KicadModTree:
C:\Users\Admin>C:\Program Files\KiCad\7.0\bin\kicad.exe -m pip install KicadModTree
I got errors. So I guessed at the syntax and finaly got some indication that there was an install. See screen dump.
![image](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/5836181/0a5f1358-e05e-48db-bac0-38ea3b3195af)
 

When in the PCB editor I refresh the plugins nothing changes.
![image](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/5836181/20aa7ae0-b65e-456a-b65f-828bdd9cdad5)

I had expected to see something added to the list just as the Fabrication Tools was added.

**Comment by TousstNicolas** [comment]
Jlc2KiCadLib is intended to be a standalone tool and not a KiCad plugin.

Therefor it is expected to not show up as a kicad plugin.

See #58

**Comment by ForrestErickson** [comment]
Thanks for getting back to me. 
I was following instructions from a fork at: https://github.com/Springer-Electronics/JLC2KiCad_lib and I did not realize the scope of your project was different.
