### ISSUE TITLE
UnboundLocalError: local variable 'datasheet_link' referenced before assignment

### ISSUE THREAD

**Issue by yosva** [TousstNicolas/JLC2KiCad_lib#7]
**Describe the bug**
Command crash after executing on single reference.

**To Reproduce**
1. C27642
2. python JLC2KiCad_lib.py C276421 -dir My_lib -schematic_lib My_Schematic_lib

**Expected behavior**
Generation of schematic and footprint

**Screenshots**
![image](https://user-images.githubusercontent.com/5352968/152815605-5c6fac9b-0328-441e-9779-27e10d254538.png)

**Additional context**
python --version
Python 3.8.6rc1

**Comment by TousstNicolas** [comment]
After further research, it seems that this component does exist, but does not appear in the JLCPCB search results, which is the reason for this error. 
I will try to find these info from another endpoint which should fix the issue.

**Comment by yosva** [comment]
Indeed I wanted to request for component C2764215 but I missed last digit. I fixed problem locally initializing datasheet_link and assembly_process at get_footprint_info. And that worked but I get the wrong component, normal, my bad.
If I request for the right parameter (C2764215) that work even without the fix. Sorry I'm rather busy in this moment, I can't  go further in the analysis. Thanks for your tool, this helped me a lot.


![image](https://user-images.githubusercontent.com/5352968/152869978-64cb9207-4572-4c23-aed5-c69d628ed323.png)

**Comment by TousstNicolas** [comment]
As the issue was only coming from the wrong argument, I only had to add better error handling. A warning message will now be printed. 
I will let you close this issue if it is ok for you.

**Comment by yosva** [comment]
It's ok for me for #7 and #8, thanks you
