### ISSUE TITLE
 Feature Request: Prefix Symbol, Footprint and 3D Model with LCSC number

### ISSUE THREAD

**Issue by jj-uk** [TousstNicolas/JLC2KiCad_lib#71]
I'd like the LCSC part number to prefix the Symbol name, Footprint Name and 3D Model name, in the format `Cxxxxx_<name>`.

This will aid finding a part in the Library without the need to "search".

**Comment by TousstNicolas** [comment]
Hi, 

The LCSC part number is already included in the "keywords" section  of each components.
Therefore you can already search for the LCSC part number  in your library.

![image](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/68825213/9b46b119-e809-4a7d-955b-bbf2ffacd3fa)
