### ISSUE TITLE
Error During Install, system cannot find...futurize.exe.deleteme

### ISSUE THREAD

**Issue by ForrestErickson** [TousstNicolas/JLC2KiCad_lib#72]
**Describe the bug**
I tried to install on a Windows 10 computer running KiCad 7.

**To Reproduce**
_Steps to reproduce the behavior:_
I typed: "pip install JLC2KiCadLib"

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expected the install to terminate normaly. It did not
![image](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/5836181/50e81491-b8fd-4b30-b216-3ef09c684898)

**Additional context**

The error : system cannot find the file specified: 'C:\\Python312\\Scripts\\futurize.exe' -> 'C:\\Python312\\Scripts\\futurize.exe.deleteme'

**Comment by TousstNicolas** [comment]
Hi, 

Unfortunately I do not have a windows installation, so I can only try to guess what the issue could be. 

Doing a quick internet search, I see that similar errors are often due to insufficient permissions. Have you tried to run the command with administrator privileges ?
